# Generated by Django 5.0.6 on 2024-06-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapela',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('jemno', models.CharField(max_length=45, unique=True)),
                ('zanr', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=45)),
                ('prijmeni', models.CharField(max_length=45)),
                ('kapela_jmeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RFPapp.kapela')),
            ],
        ),
        migrations.CreateModel(
            name='Pisnicka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno_pisne', models.CharField(max_length=45)),
                ('zanr', models.CharField(max_length=45)),
                ('kapela_jmeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RFPapp.kapela')),
            ],
        ),
    ]
