# Generated by Django 5.0.6 on 2024-06-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFPapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kapela',
            old_name='jemno',
            new_name='jmeno',
        ),
    ]
