# Generated by Django 5.0.6 on 2024-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFPapp', '0002_rename_jemno_kapela_jmeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapela',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='img/kapely'),
        ),
    ]
