# Generated by Django 5.0.6 on 2024-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFPapp', '0004_kapela_popis_alter_kapela_id_alter_osoba_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kapela',
            options={'ordering': ['jmeno'], 'verbose_name': 'Kapela', 'verbose_name_plural': 'Kapely'},
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['prijmeni', 'jmeno'], 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='pisnicka',
            options={'ordering': ['jmeno_pisne'], 'verbose_name': 'Píseň', 'verbose_name_plural': 'Písně'},
        ),
        migrations.AlterField(
            model_name='kapela',
            name='jmeno',
            field=models.CharField(max_length=45, unique=True, verbose_name='Jméno kapely'),
        ),
        migrations.AlterField(
            model_name='kapela',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='img/kapely', verbose_name='Fotka kapely'),
        ),
        migrations.AlterField(
            model_name='kapela',
            name='popis',
            field=models.TextField(blank=True, verbose_name='Popis kapely'),
        ),
        migrations.AlterField(
            model_name='kapela',
            name='zanr',
            field=models.CharField(max_length=45, verbose_name='Žánr kapely'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='jmeno',
            field=models.CharField(max_length=45, verbose_name='Jméno osoby'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='prijmeni',
            field=models.CharField(max_length=45, verbose_name='Příjmení osoby'),
        ),
        migrations.AlterField(
            model_name='pisnicka',
            name='jmeno_pisne',
            field=models.CharField(max_length=45, verbose_name='Jméno písně'),
        ),
        migrations.AlterField(
            model_name='pisnicka',
            name='zanr',
            field=models.CharField(max_length=45, verbose_name='Žánr písně'),
        ),
    ]
